### ISSUE TITLE
Children elements not displayed properly on Android

### ISSUE THREAD

**Issue by alexandrumic** [jasongaare/react-native-walkthrough#19]
Hello,

Not sure if this is an issue for this repo or for https://github.com/jasongaare/react-native-walkthrough-tooltip but I have the following behaviour: 
I've integrated the library in my project, on iOS everything works well after some small styling tweaks but on Android, every highlighted element is changing it's position (usually it appears lower than the child element) - screenshots attached.

I have tried to change some style properties but for Android the issue remains.

Do you know what can be wrong?

Thanks!

Android:
<img src="https://user-images.githubusercontent.com/49684634/96418088-f089f000-11fa-11eb-99f4-11e2909ec3e3.png" width="320">

iOS:
<img src="https://user-images.githubusercontent.com/49684634/96418099-f384e080-11fa-11eb-801f-3934dabe2d83.png" width="320">

**Comment by jasongaare** [comment]
👋  this unfortunately is a known issue with the tooltip library, but there is a workaround. You can pass a value to `topAdjustment` the tooltip using `tooltipProps` with this library here.

Please check this PR as a reference: https://github.com/jasongaare/react-native-walkthrough-tooltip/pull/69

**Comment by alexandrumic** [comment]
That worked, thank you 👍 ! Will close this because is a known issue
