### ISSUE TITLE
Overriding tooltip prop onClose of WalkthroughEvent makes tooltip impossible to close

### ISSUE THREAD

**Issue by RKuerten** [jasongaare/react-native-walkthrough#23]
As the title says, whenever you override the onClose function of the tooltip, it makes the tooltip impossible to be closed.

I tried to override it because I need to scroll down the screen (as exemplified in issue [#11](https://github.com/jasongaare/react-native-walkthrough/issues/11#issuecomment-598793098)), but I can't make it work properly, since I can't access the WalkthroughEvent ref to force it to close or go the next. Passing an `dispatchWalkthroughEvent` to the next event doesn't work either. 

```javascript
<ScrollView ref={(ref) => (this.scrollView = ref)}>
  <WalkthroughElement
    id="element-1"
    tooltipProps={{
      onClose: () => this.scrollView.scrollToBottom({ animated: true })
    }}
  >
    <Element1>
  </WalkthroughElement>
  <WalkthroughElement id="element-2">
    <Element2>
  </WalkthroughElement>
</ScrollView>
```

**Comment by RKuerten** [comment]
Okay, `goToWalkthroughElementWithId` works. I will try to make a pull request to update the readme to cover this and then close this issue.

**Comment by j-cheung** [comment]
also ran into this problem when overriding the onClose function at the end of a walkthrough.

temporarily using `startWalkthrough([{ id: "end", content: null }])` to end the walkthrough / hide the tooltip.

not sure if thats the correct way.
